Matrix
MetaColon/Numericat pull request #22
Opened 2020-12-26 10:14 UTC by TomHrm

2020-12-26 20:37 UTC, MetaColon requested changes
A few things should be adjusted. Feel free to comment on comments if you feel differently.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +double GetRandomNumber(double minimum, double maximum)
I'm not sure this belongs to matrix utility. Why do we need random support anyway?

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +    {
I personally don't like useless curly braces. We can decide to use them sometimes, enforce them always, or never use them when possible - but we should decide on it.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +            m->matrix[i][j] = (double)rand() / (double)(RAND_MAX / 10);
Why don't you use your custom random function here?

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +void freeMatrix(Matrix *a)
Why do we use a pointer to a matrix here? Aside from this free function, we usually seem to work with the struct itself.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +    Matrix temp = {r, c, calloc(r, sizeof(double *))};
Why `temp`? Isn't this the result?
And it would be better to name the parameters of the function (i.e. `{.rows=r, ...}`) - otherwise this isn't very intuitive.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +    temp.rowSize = r;
This seems like an unnecessary duplicate - it should already be set, shouldn't it?

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +        fprintf(stderr, "Empty Matrix not allowed\n");
Why should the matrix parameter be `NULL` when the matrix is created emptily? Doesn't this rather point to insufficient memory for `alloc`?

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +            fprintf(stderr, "Empty Matrix Element not allowed\n");
See above

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +void randomize(Matrix *m)
Note that you shouldn't _need_ a pointer here, as the matrix elements are referenced by a pointer anyways. It doesn't hurt neither though.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +    for(i = 0; i < m->rowSize ; i++){
I don't like this indentation style very much. I would suggest to consequently use K&R:
```
void foo()
{
    // ...
}
```

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +    return (**m->matrix + r * m->rowSize + c);
It's not clear what is dereferenced by `*` here - parentheses would probably help (though the outer parentheses are useless and should be removed)

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +        exit(0);
That's a weird exit code for error situations.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +double determinant(double **a, int n)
Use `Matrix` instead of a 2D array here.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +    int i, j, j1, j2;
Those are horrible variable names.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +        fprintf(stderr, "dimension is < 1");
The determinant of a 0x0 matrix is 0, isn't it? Not important though, as it's quite a useless usecase.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +    { /* Shouldn't get used */
Why shouldn't this get used?

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +        for (j1 = 0; j1 < n ; j1++) {
This whole `else` block should get reformatted - maybe GitHub displays the indentation wrong? It looks very weird.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +            }
Comments might help in understanding what this does. Is this a known algorithm for calculating the determinant?

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +   int i,j,ii,jj,i1,j1;
Once again, horrible variable names.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +    Matrix Inverse = createMatrix(a->rowSize, a->columnSize);
Don't use uppercase naming for local variables (I'm sure this isn't the only place this happened).

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +            Inverse.matrix[i][j] = (1/det) *  Adj.matrix[i][j];
It might be useful to check the determinant first.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +// only works for n x n at the moment
This should be validated inside the function then.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.h
> +double GetRandomNumber(double minimum, double maximum);
Inconsistent function naming - should be lowercase.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Tests/Check_Matrix.h
> +
Useless whitespace

2020-12-26 20:37 UTC, MetaColon commented on Backend/Tests/Check_Matrix.h
> +    Matrix_1.matrix[0][0] = 2.0;
This seems like a very specific case - different values should be tested.

2020-12-26 20:37 UTC, MetaColon commented on Backend/Tests/Check_Matrix.h
> +    Matrix Matrix_1 = createMatrix(2,2);
Not only 2x2 matrices should be tested (especially as the function acts differently for 2x2)

2020-12-26 20:37 UTC, MetaColon commented on Backend/Tests/Check_Matrix.h
> +    ck_assert(multiplied.matrix[0][0] == 8.0);
Don't test for equality with floating points - always allow a difference of something like 0.00001 or similar.

2020-12-27 11:16 UTC, TomHrm commented on Backend/Solver/Matrix/Utility.c
> +double GetRandomNumber(double minimum, double maximum)
removed it

2021-01-02 11:39 UTC, TomHrm commented on Backend/Solver/Matrix/Utility.c
> +        fprintf(stderr, "Empty Matrix not allowed\n");
It should never be NULL, yap. This is just in case something went wrong

2021-01-02 11:42 UTC, TomHrm commented on Backend/Solver/Matrix/Utility.c
> +    { /* Shouldn't get used */
It can be used but prob never will

2021-01-02 11:44 UTC, TomHrm commented on Backend/Solver/Matrix/Utility.c
> +            }
This is called "determinant expansion by minor"

2021-01-02 11:58 UTC, TomHrm commented on Backend/Solver/Matrix/Utility.c
> +            fprintf(stderr, "Empty Matrix Element not allowed\n");
just wanted to test if that's ever the case, should not be possible

2021-01-02 11:59 UTC, TomHrm commented on Backend/Solver/Matrix/Utility.c
> +    temp.rowSize = r;
why should it already be set?

2021-01-02 16:08 UTC, MetaColon requested changes

2021-01-02 16:08 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +        exit(0);
I don't think that's resolved.

2021-01-02 16:10 UTC, MetaColon requested changes

2021-01-02 16:10 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +    temp.rowSize = r;
By the initialisation with `{r, c, ...}`

2021-01-02 17:56 UTC, TomHrm commented on Backend/Solver/Matrix/Utility.c
> +    Matrix temp = {r, c, calloc(r, sizeof(double *))};
this version is outdated

2021-01-02 17:56 UTC, TomHrm commented on Backend/Solver/Matrix/Utility.c
> +        exit(0);
outdated aswell

2021-01-03 18:26 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +        exit(0);
Then you'll need to push the changes before requesting another review

2021-01-03 18:28 UTC, MetaColon approved these changes

2021-01-03 18:28 UTC, merged