Crank nickelson#3
MetaColon/Numericat pull request #26
Opened 2021-01-17 21:25 UTC by TomHrm

2021-01-19 09:10 UTC, MetaColon requested changes
Just a few small changes required. Please note that, as I did a lot of edits in this branch too, you should review my changes as well.

2021-01-19 09:10 UTC, MetaColon commented on Backend/Solver/CrankNicolson/Iteration.c
> +#include <stdio.h>
This file should be deleted

2021-01-19 09:10 UTC, MetaColon commented on Backend/Solver/CrankNicolson/Iteration.h
> +#ifndef BACKEND_NICKELSON_H
This file should also be deleted.

2021-01-19 09:10 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +            //result[i][j] = a[i][j]+b[i][j]
We don't need commented code.

2021-01-19 09:10 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +            //result[i][j] = a[i][j]-b[i][j]
See above

2021-01-19 09:10 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +        fprintf(stderr, "Error: columns of Matrix a != rows of Matrix b");
Wrong error message

2021-01-19 09:10 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +        exit(0);
0 is not an error exit code

2021-01-19 09:10 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +        fprintf(stderr, "Error: columns of Matrix a != rows of Matrix b");
See above

2021-01-19 09:10 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
> +// n is the dimension of a.matrix
This comment doesn't seem valid anymore

2021-01-19 09:10 UTC, MetaColon commented on Backend/Tests/Check_Matrix.h
> +    input.matrix[0][0] = 2.0;
The matrices for the tests shouldn't have the same value in all columns. E.g.

    1 2
    3 4
would be a better testcase, as it ensures the correct ordering is preserved.

This is not only relevant for `test_factor`, but also for the other tests.

2021-01-19 09:10 UTC, MetaColon commented on Backend/Tests/Check_Matrix.h
> +    printf("results should: \n");
There is no validation happening here

2021-01-20 09:26 UTC, MetaColon requested changes
Just one adjustment needed.

2021-01-20 09:26 UTC, MetaColon commented on Backend/Solver/Matrix/Utility.c
>          fprintf(stderr, "Error: columns of Matrix a != rows of Matrix b");
This error message is still wrong

2021-01-20 10:05 UTC, TomHrm commented on Backend/Program.c
> +        fprintf(stderr, "Expected %s <potential function> <initial function> (2 arguments), but got %d argument%s\n",
Is Github displaying the Format wrong here?

2021-01-20 10:07 UTC, MetaColon commented on Backend/Program.c
> +        fprintf(stderr, "Expected %s <potential function> <initial function> (2 arguments), but got %d argument%s\n",
Looks alright to me in GitHub.

2021-01-20 10:24 UTC, MetaColon approved these changes

2021-01-20 10:24 UTC, merged