Sclaing#28
MetaColon/Numericat pull request #38
Opened 2021-02-06 14:26 UTC by TomHrm

2021-02-06 14:44 UTC, MetaColon requested changes

2021-02-06 14:44 UTC, MetaColon commented on Frontend/Makefile
> +	echo "Run using java package de.numericat.Main in src folder" > README
That's not correct - `package` is not reqeuired

2021-02-06 14:44 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +import java.io.File;
Why do we need this import?

2021-02-06 14:44 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +        double ScalingFactor = 0;
Local variables are written in lower camel case (`scalingFactor`)

2021-02-06 14:44 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +        int counter = 0;
What do we need this two variables for?

2021-02-06 14:44 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +                if(line != "")
Why do you apply the same scaling for both functions?

2021-02-06 14:44 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +                    System.out.println(line);
This produces way too much log

2021-02-06 14:44 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +                        if(ScalingFactor < Double.parseDouble(splitString[i]))
The value is parsed twice (pull out of if)

2021-02-06 14:44 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +            scanner.close();
Do this in `finally` (otherwise the scanner is not closed in case of an exception)

2021-02-06 14:44 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +        return 700/ScalingFactor;
Where does this magic number come from? Use properties of window or similar.

2021-02-06 14:44 UTC, MetaColon commented on Frontend/src/de/numericat/Numericanvas.java
> +
Why do we need an extra space here?

2021-02-06 15:32 UTC, TomHrm commented on Frontend/src/de/numericat/Main.java
> +                if(line != "")
I dont know what you mean

2021-02-06 18:37 UTC, MetaColon requested changes

2021-02-06 18:37 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +            scanner.close();
The file input stream needs to be closed too. Note that I didn't do either of that, so feel free to correct it for `getData` as well

2021-02-06 19:45 UTC, MetaColon requested changes

2021-02-06 19:45 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +            String[] splitString = line.split(" ");
The potential is time dependent too - that means that you need to find a global maximum for the potential in the same way you do for the wave function.
Please avoid code repetition though and put this in a loop instead.

2021-02-06 19:45 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +            System.out.println(line);
Do we need this print?

2021-02-06 19:45 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +            double el = (canvas.getHeight() / scalingFactor[0]) * Double.parseDouble(split[i]);
You'll still need to pass a parameter to indicate _which_ scaling factor to apply

2021-02-07 10:10 UTC, MetaColon requested changes

2021-02-07 10:10 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +    private static List<Coordinate> potentiallineToCoordinates(String line) {
Useless code duplicate. Why don't you just pass the index for the scaling factor as a parameter?

2021-02-07 13:17 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +    private static List<Coordinate> potentiallineToCoordinates(String line) {
Please don't mark change requests as resolved until the requested changes are committed.

2021-02-07 17:59 UTC, MetaColon requested changes

2021-02-07 17:59 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +            if(potential == true)
Seriously?

2021-02-07 17:59 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +                el = (height / scalingFactor[1]) * Double.parseDouble(split[i]);
Why don't you just pass the _index_ as an argument?

2021-02-07 17:59 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +            potential_scanner = new Scanner(inputStream_2);
Why do you use two scanners?

2021-02-07 17:59 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +            while(potential_scanner.hasNext() && potential_scanner.nextLine() != "") {
Why don't you use the existing method to jump to the potential part?

2021-02-07 18:11 UTC, TomHrm commented on Frontend/src/de/numericat/Main.java
> +            potential_scanner = new Scanner(inputStream_2);
because now it evaluetes the first line of each function at the while iteration

2021-02-07 18:11 UTC, TomHrm commented on Frontend/src/de/numericat/Main.java
> +            while(potential_scanner.hasNext() && potential_scanner.nextLine() != "") {
Like what method? I did not find any

2021-02-07 20:00 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +            while(potential_scanner.hasNext() && potential_scanner.nextLine() != "") {
`skipTillEmptyLine`

2021-02-07 20:01 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +            potential_scanner = new Scanner(inputStream_2);
But now you also have more code duplicates. You should make a method like `findMaximumOfBlock` or similar, that gets a scanner as parameter (that is set to the start of the block) and then finds the maximum.

2021-02-07 20:40 UTC, TomHrm commented on Frontend/src/de/numericat/Main.java
> +            while(potential_scanner.hasNext() && potential_scanner.nextLine() != "") {
I thought each scanner has its own line and I increase it with nextLine(), but if I now use skipTillEmptyLine then I am directly in the potential, so I can only omit the above While loop?

2021-02-07 22:09 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +            while(potential_scanner.hasNext() && potential_scanner.nextLine() != "") {
You implement a function `findMaximumOfBlock`, call this function on the initial scanner to obtain the maximum for the wave function and then (you won't even need `skipTillEmptyLine` anymore) you call the same method again, with the same scanner, to obtain the maximum for the potential.

2021-02-07 22:22 UTC, TomHrm commented on Frontend/src/de/numericat/Main.java
> +            while(potential_scanner.hasNext() && potential_scanner.nextLine() != "") {
Done. Is there any real advantage besides it being more readable and not using 2 scanners?

2021-02-07 22:22 UTC, MetaColon requested changes

2021-02-07 22:22 UTC, MetaColon commented on Frontend/src/de/numericat/Main.java
> +        while(scanner.hasNextLine() && scanner.nextLine() != "") {
You always skip one line, by reading the next line but not storing it (this also causes an exception)

2021-02-07 22:42 UTC, MetaColon approved these changes

2021-02-07 22:45 UTC, merged