Mormalizing #37
MetaColon/Numericat pull request #47
Opened 2021-02-17 08:27 UTC by TomHrm

2021-02-17 10:46 UTC, MetaColon requested changes

2021-02-17 10:46 UTC, MetaColon commented on Backend/Solver/CrankNicolson/Iterate.c
> +    for (int i = 0; i < n; i++) {
Wrong brace style

2021-02-17 10:46 UTC, MetaColon commented on Backend/Solver/CrankNicolson/Iterate.c
> +        double result = 0;
`result` is a misleading variable name

2021-02-17 10:46 UTC, MetaColon commented on Backend/Solver/CrankNicolson/Iterate.c
> +
Why do we need this blank line?

2021-02-17 10:46 UTC, MetaColon commented on Backend/Solver/CrankNicolson/Iterate.c
> +static Complex **normalize(Complex **res, int n) {
Making this method return `res` implies that it is immutable (which it isn't)

2021-02-17 10:46 UTC, MetaColon commented on Backend/Solver/CrankNicolson/Iterate.c
> +    res = normalize(res, n);
The assignment to `res` is redundant, as the parameter is already altered.

2021-02-17 23:21 UTC, MetaColon requested changes

2021-02-17 23:21 UTC, MetaColon commented on Backend/Solver/CrankNicolson/Iterate.c
> +        res = normalize(res, n);
As you normalize _all_ values, you only need to call `normalize` once (e.g. at the end)

2021-02-17 23:22 UTC, MetaColon commented on Backend/Solver/CrankNicolson/Iterate.c
> +    res = normalize(res, n);
You didn't adress this.

2021-02-17 23:22 UTC, MetaColon commented on Backend/Solver/CrankNicolson/Iterate.c
> +static Complex **normalize(Complex **res, int n) {
You didn't adress this.

2021-02-17 23:49 UTC, TomHrm commented on Backend/Solver/CrankNicolson/Iterate.c
> +static Complex **normalize(Complex **res, int n) {
which return type is appropriate?

2021-02-18 08:23 UTC, MetaColon commented on Backend/Solver/CrankNicolson/Iterate.c
> +static Complex **normalize(Complex **res, int n) {
`void`

2021-02-18 10:23 UTC, MetaColon requested changes

2021-02-18 10:23 UTC, MetaColon commented on Backend/Solver/CrankNicolson/Iterate.c
> +void normalize(Complex **normalized, int n)
This parameter name is misleading, as it isn't normalized by the time the method is called

2021-02-18 10:23 UTC, MetaColon commented on Backend/Solver/CrankNicolson/Iterate.c
> +    normalize(res, n);
The normalization should be done _after_ the last value is written to `res`

2021-02-18 10:38 UTC, MetaColon approved these changes

2021-02-18 11:14 UTC, merged